[Description("Entity to represent the Subnet specified in the dhcp.conf file.")
]

class Linux_DHCPSubnet : Linux_DHCPEntity {

	[Description("This Attribute would sepcify the subdivision of the given network."),
	Write]
	string Netmask;
	
	
	};
		
